import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";

import { CssBaseline, ThemeProvider } from "@mui/material";
import { baselightTheme } from "@/utils/theme/DefaultColors";
import Provider from "./providers/ClientProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const session = await getServerSession(authOptions);
    return (
        <html lang="en">
            <body>
                <ThemeProvider theme={baselightTheme}>
                    <CssBaseline />

                    <Provider session={session}>
                        <div className="container">{children}</div>
                    </Provider>
                </ThemeProvider>
            </body>
        </html>
    );
}
